COL_A = 'D' # Detail Record ID 
COL_B = ['NYU Hospitals Center', 'NYU Langone Health System', 'NYU School of Medicine'] # Employer Name 
COL_C = ['13-3971298', '47-2613531', '13-5562309'] # Employer EIN 
COL_D = ['151562', '151576', '151579', '403400', '403401', '407140', '407141'] # Employer Plan ID  
COL_E = ['GA1', 'GS1'] # Employer Sub Plan ID 
COL_F = []#['151562', '151576', '151579', '403400', '403401', '407140', '407141'] # Originating Vendor Plan ID
COL_G = []#['GA1', 'GS1'] # Originating Vendor Sub Plan ID 
COL_H = []#['151562', '151576', '151579', '403400', '403401', '407140', '407141'] # Recipient Vendor Plan ID 
COL_I = []#['GA1', 'GS1'] # Recipient Vendor Sub Plan ID 
COL_J = ['001', '007', '008', '009', '01A', '01K', '457'] # Type of Account 
COL_K = ['1', '2', '4', '12', '24', '26', '52', '365'] # Payroll Frequency 
COL_L = 100000001 #Employee SSN - seed value
COL_M = ' ' # Employee ID, samme as SSN
COL_N = ' ' #Mr/ Mrs/ Dr
COL_O = '' #FIRST NAME
COL_P = '' #MIDDLE NAME
COL_Q = '' #LAST NAME
COL_R = '' #street
COL_S = '' #Apt/Suit
COL_T = ' ' #' '
COL_U = '' #state
COL_V = '' #short form
COL_W = '' #zipcode
COL_X = 'US' #US
COL_Y = ['U', 'N'] # Residency Code 
COL_Z = ' ' #' ' // Employee DOB 
COL_AA = ['M', 'F'] # Gender ID 
COL_AB = ['M', 'S', 'P', 'Q'] # Marital Status 
COL_AC = ' ' # Phone Number 1 
COL_AD = ' ' # Phone Number type
COL_AE = ' '
COL_AF = ' '
COL_AG = ' '
COL_AH = ' '
COL_AI = ' ' # Business Email Address 
COL_AJ = '' #  Personal Email Address  
COL_AK = '' # Payroll Date   Employee Plan Remittance Data 23
COL_AL = ['F', 'E'] # Contribution Source Code 1 
COL_AM = '' # Contribution Source Amount 1
COL_AN = ['F', 'E'] # Contribution Source Code 2 
COL_AO = '' # Contribution Source Amount 2
COL_AP = ['F', 'E'] # Contribution Source Code 3
COL_AQ = '' # Contribution Source Amount 3
COL_AR = ['F', 'E'] # Contribution Source Code 4
COL_AS = '' # Contribution Source Amount 4
COL_AT = ['F', 'E'] # Contribution Source Code 5 
COL_AU = '' # Contribution Source Amount 5
COL_AV = ['F', 'E'] # Contribution Source Code 6
COL_AW = '' # Contribution Source Amount 6
COL_AX = ['F', 'E'] # Contribution Source Code 7 
COL_AY = '' # Contribution Source Amount 7
COL_AZ = ['F', 'E'] # Contribution Source Code 8
COL_BA = '' # Contribution Source Amount 8
COL_BB = '' # Final Contribution Indicator 
COL_BC = '' # Loan Number 1 
COL_BD = '' # Loan Repayment Amount 1 
COL_BE = '' # Loan Number 2
COL_BF = '' # Loan Repayment Amount 2
COL_BG = '' # Loan Number 3
COL_BH = '' # Loan Repayment Amount 3
COL_BI = '' # Loan Number 4
COL_BJ = '' # Loan Repayment Amount 4
COL_BK = '' # Loan Number 5
COL_BL = '' # Loan Repayment Amount 5
COL_BM = '' # HR Area/ Location code Employee Employment Data
COL_BN = '' # HR Sub Area 
COL_BO = '' # Original Date of Hire 
COL_BP = '' # Adjusted Date of Hire 
COL_BQ = ['E', 'D', 'P', 'R', 'T', 'L'] # Employment Status 
COL_BR = '' # Employment Sub Type
COL_BS = '' # Employment Status Date 
COL_BT = ['F', 'P', 'L', 'T'] # Employee Type 
COL_BU = '12'
COL_BV = '' # Years of Service 
COL_BW = '' # Months of Service 
COL_BX = '' # Annual Salary 
COL_BY = '' # Cash Bonus Amount 
COL_BZ = '' # Per Pay Compensation 
COL_CA = '' # Per Pay Hours Worked
COL_CB = '' # Year to Date Type 
COL_CC = '' # Year to Date Base Compensation 
COL_CD = '' # Year to Date Total Compensation 
COL_CE = '' # Year to Date Hours Worked 
COL_CF = ['Y', 'N'] # HCE Flag 
COL_CG = ['Y', 'N'] # Key Employee Flag 
COL_CH = ['Y', 'N'] # Union Employee Flag 
COL_CI = '' # Employee Plan Status  - Employee Plan Enrollment Data 
COL_CJ = '' # Plan Entry Date 
COL_CK = '' # Vested Date 
COL_CL = '' # Alternate Vesting Start Date 
COL_CM = '' # Vesting Source Code 1 
COL_CN = '' # Vesting Percentage 1 
COL_CO = '' # Vesting Source Code 2 
COL_CP = '' # Vesting Percentage 2
COL_CQ = '' # Vesting Source Code 3 
COL_CR = '' # Vesting Percentage 3
COL_CS = '' # Contribution Source Code 1 
COL_CT = '' # Deferral Percentage CS1
COL_CU = '' # Per Pay Deferral Amount  CS1
COL_CV = '' # Contribution Source Code 2
COL_CW = '' # Deferral Percentage  CS2
COL_CX = '' # Per Pay Deferral Amount  CS2
COL_CY = '' # Contribution Source Code 3
COL_CZ = '' # Deferral Percentage  CS3
COL_DA = '' # Per Pay Deferral Amount  CS3
COL_DB = '' # Plan Annual Salary 
COL_DC = '' # Employer Contribution Eligibility Source 1 
COL_DD = '' # Employer Contribution Eligibility Date 1 
COL_DE = '' # Employer Contribution Eligibility Source 2 
COL_DF = '' # Employer Contribution Eligibility Date 2
COL_DG = ['N/A', 'AUTO', 'OUT', 'SELF'] # Automatic Deferral Increase Type 
COL_DH = '' # Automatic Deferral Increase Election Date 
COL_DI = '' # Automatic Deferral Increase Next Increase Date 
COL_DJ = '' # Automatic Deferral Increase End Date 
COL_DK = ['1', '2', '4'] # Automatic Deferral Increase Frequency 
COL_DL = '' # Automatic Deferral Increase Amount 
COL_DM = '' # Automatic Deferral Increase Amount Maximum 
COL_DN = '' # Automatic Deferral Increase Percentage 
COL_DO = '' # Automatic Deferral Increase Percentage Maximum 


COL_RANDOM = [0, 1, 2]

